### ISSUE TITLE
Table component has scroll bar instead of wrapping text

### ISSUE THREAD

**Issue by TanyaStere42** [WildMeOrg/codex-frontend#550]
## Current Behavior
Table component doesn't wrap, creating a scroll bar that is difficult to find if the table is longer than the page
![image](https://github.com/WildMeOrg/codex-frontend/assets/62726866/b15e80a1-f7f9-469e-9c83-8bc5e5557c97)

## Expected Behavior
Table contents wrap
![image](https://github.com/WildMeOrg/codex-frontend/assets/62726866/ab43ee64-a4e1-4877-9e37-8c4997dd6e9c)

##QA Checklist
- [ ] collaboration table wraps correctly, no longer displays horizontal scroll
- [ ] change log table wraps correctly, no longer displays the horizontal scroll

**Comment by mustachemo** [comment]
hello, where can i find the file collaboration and change log tables?

**Comment by naknomum** [comment]
> I was trying to setup the system that's when I faced an issue , I was setting up houston and for some reason when I tried to execute commands it kept giving me error "Top-level object must be a mapping "

hello. can you give me a little more context on when/where you were getting this error during the setup?   thx

**Comment by TanyaStere42** [comment]
> hello, where can i find the file collaboration and change log tables?

Hi @mustachemo ! This ticket is actually already assigned to someone else and in progress. I can help you find something similar to start on if you're interested?

**Comment by raaaaj214** [comment]
Sure , I am open to work on any issues provided.  Sent from Mail for Windows From: TanyaSent: 09 September 2023 04:29To: WildMeOrg/codex-frontendCc: Raj Deshmukh; CommentSubject: Re: [WildMeOrg/codex-frontend] Table component has scroll bar instead of wrapping text (Issue #550) hello, where can i find the file collaboration and change log tables?Hi @mustachemo ! This ticket is actually already assigned to someone else and in progress. I can help you find something similar to start on if you're interested?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by raaaaj214** [comment]
I got the error when I was setting up Houston .  Sent from Mail for Windows From: Jon Van OastSent: 08 September 2023 22:07To: WildMeOrg/codex-frontendCc: Raj Deshmukh; CommentSubject: Re: [WildMeOrg/codex-frontend] Table component has scroll bar instead of wrapping text (Issue #550) I was trying to setup the system that's when I faced an issue , I was setting up houston and for some reason when I tried to execute commands it kept giving me error "Top-level object must be a mapping "hello. can you give me a little more context on when/where you were getting this error during the setup? thx—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by TanyaStere42** [comment]
@raaaaj214 and @naknomum , I've created a different issue for you to continue the trouble shooting on. Ticket number #552
